name: Release to NPM

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - uses: ./.github/actions/test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Setup pnpm 📦️
        uses: pnpm/action-setup@v6

      - name: Use Node ✨
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Build 🔨
        run: pnpm build

      - name: Publish to NPM 📦️
        uses: simenandre/publish-with-pnpm@v2
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
